### ISSUE TITLE
Application crashes after 'Finished all tasks' - Pihole Adblocker blocking DNS.

### ISSUE THREAD

**Issue by Lewis-Fam** [L0um15/Spotisharp#26]
**Describe the bug**
The application crashes after all tasks are finished. 

I use pihole adblocker I am blocking youtube ad servers.    Here is a link to the domains I am blocking: **https://raw.githubusercontent.com/Lewis-Fam/pihole_adlists/main/youtube_ads_blocklist.txt**

--- Message ---
The requested name is valid, but no data of the requested type was found. (rr3---sn-qxoedne7.googlevideo.com:443)

**How To Reproduce**
Crashes on playlists and albums. I didn't test tracks.

**Include latest log file**
..
....
......
[2022.09.09 19:40:32] [Debug]: W #2 ::: Finished current task ::: Case   Point - Savage
[2022.09.09 19:40:32] [Info]: W #2 ::: Skipping: Tut Tut Child - Fat Cat Adventures                                                                 
[2022.09.09 19:40:33] [Info]: W #2 ::: Skipping: Noisia - Mundus Theme                                                                              
[2022.09.09 19:40:33] [Info]: W #2 ::: Skipping: Adventure Club - Gold (feat. Yuna)                                                                 
[2022.09.09 19:40:33] [Info]: W #2 ::: Skipping: Knife Party - Kaleidoscope                                                                         
[2022.09.09 19:40:34] [Info]: W #2 ::: Finished all tasks                                                                                           
[2022.09.09 19:40:34] [Debug]: W #1 ::: Downloading ::: Linkin Park - LOST IN THE ECHO - KillSonik Remix
[2022.09.09 19:40:37] [Debug]: W #1 ::: Converting ::: Linkin Park - LOST IN THE ECHO - KillSonik Remix
[2022.09.09 19:40:42] [Debug]: W #1 ::: Adding metadata ::: Linkin Park - LOST IN THE ECHO - KillSonik Remix
[2022.09.09 19:40:42] [Debug]: W #1 ::: Finished current task ::: Linkin Park - LOST IN THE ECHO - KillSonik Remix
[2022.09.09 19:40:42] [Info]: W #1 ::: Finished all tasks                                                                                           
[2022.09.09 19:40:42] [Error]: Application crashed!

--- Message ---
**The requested name is valid, but no data of the requested type was found. (rr3---sn-qxoedne7.googlevideo.com:443)**

--- Helplink ---

--- Source ---
System.Net.Http

--- StackTrace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Spotisharp.Client.Services.YoutubeService.GetSize(String url) in W:\Daddy\Documents\dev\Spotisharp\Spotisharp.Client\Services\YoutubeService.cs:line 109
   at Spotisharp.Client.Services.YoutubeService.GetStreamAsync(String url, IProgress`1 progress) in W:\Daddy\Documents\dev\Spotisharp\Spotisharp.Client\Services\YoutubeService.cs:line 62
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in W:\Daddy\Documents\dev\Spotisharp\Spotisharp.Client\Program.cs:line 230
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in W:\Daddy\Documents\dev\Spotisharp\Spotisharp.Client\Program.cs:line 150
   at Program.<Main>(String[] args)

--- TargetSide ---
Void MoveNext()

Windows 10 and 11.

**I am able to resolve the crash by disabling pihole adblocker.**

**Comment by Lewis-Fam** [comment]
I'll run the app in debug mode today or tomorrow and see if where I can catch the error for a clean application exit.  Figured I should let you know though.

Thanks for the great app!

**Comment by L0um15** [comment]
Thank you for your contribution it this project :)

**Comment by Lewis-Fam** [comment]
:-) 

I created a pull request. The HttpResponseMessage.Content.Headers.ContentLength is a nullable long. This allows the GetSize method to throw anywhere within the request pipeline.  I then had to move the null check to the caller.  

So far so good. No issues.

**Comment by L0um15** [comment]
#27 merged. Thank you!
